#pragma once
#include "common_def.h"
#include "comdata_scan_def.h"
// CBkRescan
BKCOM_PROXY_METHOD_PARAM_BEGIN(GetRescanResult, CBkRescanOut)
    BKCOM_PROXY_METHOD_PARAM(CAtlArray<BK_FILE_RESULT>, result);
BKCOM_PROXY_METHOD_PARAM_END
BKCOM_PROXY_METHOD_PARAM_XDX_BEGIN(GetRescanResult, CBkRescanOut)
    BKCOM_PROXY_METHOD_PARAM_XDX(result)
BKCOM_PROXY_METHOD_PARAM_XDX_END
// CBkEcho
BKCOM_PROXY_METHOD_PARAM_BEGIN(Echo, CBkEcho)
    BKCOM_PROXY_METHOD_PARAM(CAtlArray<CString>, FileList);
BKCOM_PROXY_METHOD_PARAM_END
BKCOM_PROXY_METHOD_PARAM_XDX_BEGIN(Echo, CBkEcho)
    BKCOM_PROXY_METHOD_PARAM_XDX(FileList)
BKCOM_PROXY_METHOD_PARAM_XDX_END
// CBkPluginReport
BKCOM_PROXY_METHOD_PARAM_BEGIN(PluginReport, CBkPluginReport)
    BKCOM_PROXY_METHOD_PARAM(CAtlArray<BK_PLUGIN_INFO>, PluginList);
BKCOM_PROXY_METHOD_PARAM_END
BKCOM_PROXY_METHOD_PARAM_XDX_BEGIN(PluginReport, CBkPluginReport)
    BKCOM_PROXY_METHOD_PARAM_XDX(PluginList)
BKCOM_PROXY_METHOD_PARAM_XDX_END
// CBkUtility
BKCOM_PROXY_METHOD_PARAM_BEGIN(QueryLastScanInfo, CBkUtility)
    BKCOM_PROXY_METHOD_PARAM(DWORD, dwScanMode);
BKCOM_PROXY_METHOD_PARAM_END
BKCOM_PROXY_METHOD_PARAM_XDX_BEGIN(QueryLastScanInfo, CBkUtility)
    BKCOM_PROXY_METHOD_PARAM_XDX(dwScanMode)
BKCOM_PROXY_METHOD_PARAM_XDX_END
