#pragma once
#include "common_def.h"

BKCOM_PROXY_METHOD_PARAM_BEGIN(Execute, CBkServiceCall)
    BKCOM_PROXY_METHOD_PARAM(CString, strExePath)
    BKCOM_PROXY_METHOD_PARAM(CString, strCmdline)
    BKCOM_PROXY_METHOD_PARAM(BOOL, bShow);
BKCOM_PROXY_METHOD_PARAM_END
BKCOM_PROXY_METHOD_PARAM_XDX_BEGIN(Execute, CBkServiceCall)
    BKCOM_PROXY_METHOD_PARAM_XDX(strExePath)
    BKCOM_PROXY_METHOD_PARAM_XDX(strCmdline)
    BKCOM_PROXY_METHOD_PARAM_XDX(bShow)
BKCOM_PROXY_METHOD_PARAM_XDX_END