/**
* @file    slupcltdef.h
* @brief   ...
* @author  zhangrui
* @date    2009-03-05  16:32
*/

#ifndef SLUPCLTDEF_H
#define SLUPCLTDEF_H



// 版本信息中使用到的结点名
#define SLUPCLT_US_URL                      _T("Url")           ///< ...
#define SLUPCLT_US_FINDEX_URL               _T("FIndex")        ///< ...
#define SLUPCLT_US_FINDEX_HASH              _T("FIndexHash")    ///< ...
#define SLUPCLT_US_FINDEX_URL_ROOT          _T("FindexPath")    ///< ...
#define SLUPCLT_US_NAME                     _T("Name")          ///< ...
#define SLUPCLT_US_VERSION                  _T("Ver")           ///< ...
#define SLUPCLT_US_MODULE                   _T("Module")        ///< ...
#define SLUPCLT_US_FILE                     _T("File")          ///< ...
#define SLUPCLT_US_FILE_HASH                _T("Hash")          ///< ...
#define SLUPCLT_US_FILE_SIZE                _T("Size")          ///< ...
#define SLUPCLT_US_INDEX                    _T("Index")         ///< ...

// 本地使用
#define SLUPCLT_USMK_NEED_UPDATE            _T("_NeedUpdate")   ///< ...
//#define SLUPCLT_USMK_NEED_RENEW             _T("_NeedRenew")



#endif//SLUPCLTDEF_H